#!/usr/bin/env bash

set -eou pipefail

rm -rf built/

GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o built/kubano

docker build -t polygonio/sandbox:drone-plugin-kube .
docker push polygonio/sandbox:drone-plugin-kube
